"""Frozen UID test vectors -- an oracle independent of the implementation.

Requirement 9 of the P0-2 brief, and the reason it exists: every other test in
this repo builds its expected UID by calling `policy_uid.compute_uid()`, the
same function under test. A derivation that is wrong in the same way on both
sides agrees with itself, and the whole suite passes green while the identity
scheme means something other than what it documents.

The constants below are therefore NOT computed at test time and MUST NOT be
regenerated by calling production code. They were produced once by a standalone
reimplementation of the documented rule -- SHA-256 over

    canonical_v1 \\0 kind \\0 source_pdf_sha256 \\0 physical_page \\0
    NFC(span text) \\0 ordinal \\0 parent_uid \\0 column_key

truncated to 16 hex characters and prefixed by the kind's tag, with a multi-span
object's "span text" being its child span UIDs in canonical source order joined
by \\x1f.

If a change to the derivation makes these fail, that is the test doing its job:
the UIDs of every canonical artifact in existence just changed. Update a vector
only as a deliberate, documented scheme change -- never to make a red suite
green.
"""
import policy_uid
import policy_uid_resolver


PDF = "a" * 64
SEP = "\x1f"

# Page 3 of the immutable parent, two spans.
QUOTE_A = "제3조(보험금의 지급)"
QUOTE_B = "회사는 보험금을 지급합니다"

VECTORS = {
    "PS_first_occurrence": "PS-3ddd1b72682edbbf",
    "PS_second_span": "PS-5e5e7a1b76e00b50",
    "PS_same_text_second_occurrence": "PS-e8631a34fb66d694",
    "PB_two_spans": "PB-13b1cb71c2059f07",
    "PC_under_that_boundary": "PC-3dc95b61e7524b8e",
    "CI_under_that_clause": "CI-0f1611a251077764",
    "RT_source_region_span": "PS-10126d1b1c4b4236",
    "RT_one_region": "RT-15c0cec9df4e388c",
    "RR_row_span": "PS-8569abbcae6580f5",
    "RR_under_that_table": "RR-43243a117464e103",
    "RC_cell_span": "PS-af74db44aea1aab4",
    "RC_under_that_row": "RC-74563157681aa59f",
}


# --- PS --------------------------------------------------------------------

def test_ps_vector():
    assert policy_uid.compute_uid(
        "span", source_pdf_sha256=PDF, physical_page=3,
        span_text=QUOTE_A) == VECTORS["PS_first_occurrence"]


def test_ps_second_span_vector():
    assert policy_uid.compute_uid(
        "span", source_pdf_sha256=PDF, physical_page=3,
        span_text=QUOTE_B) == VECTORS["PS_second_span"]


def test_ps_occurrence_ordinal_changes_the_vector():
    """Same bytes, same page, second occurrence -- a different element."""
    second = policy_uid.compute_uid(
        "span", source_pdf_sha256=PDF, physical_page=3, span_text=QUOTE_A,
        ordinal=2)
    assert second == VECTORS["PS_same_text_second_occurrence"]
    assert second != VECTORS["PS_first_occurrence"]


# --- PB / PC / CI ----------------------------------------------------------

def test_pb_vector_over_two_spans():
    assert policy_uid.compute_uid(
        "boundary", source_pdf_sha256=PDF, physical_page=3,
        span_text=SEP.join([VECTORS["PS_first_occurrence"],
                            VECTORS["PS_second_span"]]),
    ) == VECTORS["PB_two_spans"]


def test_pc_vector_carries_its_parent_boundary():
    assert policy_uid.compute_uid(
        "clause", source_pdf_sha256=PDF, physical_page=3,
        span_text=VECTORS["PS_first_occurrence"],
        parent_uid=VECTORS["PB_two_spans"],
    ) == VECTORS["PC_under_that_boundary"]


def test_ci_vector_carries_its_parent_clause():
    assert policy_uid.compute_uid(
        "condition", source_pdf_sha256=PDF, physical_page=3,
        span_text=VECTORS["PS_second_span"],
        parent_uid=VECTORS["PC_under_that_boundary"],
    ) == VECTORS["CI_under_that_clause"]


# --- RT / RR / RC ----------------------------------------------------------

def test_rt_vector():
    region = policy_uid.compute_uid(
        "span", source_pdf_sha256=PDF, physical_page=7,
        span_text="A 10\nB 20")
    assert region == VECTORS["RT_source_region_span"]
    assert policy_uid.compute_uid(
        "table", source_pdf_sha256=PDF, physical_page=7,
        span_text=region) == VECTORS["RT_one_region"]


def test_rr_vector_carries_its_parent_table():
    row_span = policy_uid.compute_uid(
        "span", source_pdf_sha256=PDF, physical_page=7, span_text="A 10")
    assert row_span == VECTORS["RR_row_span"]
    assert policy_uid.compute_uid(
        "row", source_pdf_sha256=PDF, physical_page=7, span_text=row_span,
        parent_uid=VECTORS["RT_one_region"],
    ) == VECTORS["RR_under_that_table"]


def test_rc_vector_carries_its_parent_row_and_column():
    cell_span = policy_uid.compute_uid(
        "span", source_pdf_sha256=PDF, physical_page=7, span_text="10")
    assert cell_span == VECTORS["RC_cell_span"]
    assert policy_uid.compute_uid(
        "cell", source_pdf_sha256=PDF, physical_page=7, span_text=cell_span,
        parent_uid=VECTORS["RR_under_that_table"], column_key="rate",
    ) == VECTORS["RC_under_that_row"]


# --- the resolver's own composition agrees with the vectors ----------------

def _records(*specs):
    """Identity records shaped as the resolver builds them."""
    return [
        {"uid": uid, "physical_page": page, "start_char": start,
         "end_char": end, "quote": "", "ordinal": 1, "logical_page": page}
        for uid, page, start, end in specs
    ]


def _context():
    return policy_uid_resolver.SourceContext(
        "DOC_005", PDF, {}, lambda page: page)


def test_the_resolver_composes_the_frozen_pb():
    """Not just `compute_uid` -- the resolver's ordering and joining, which is
    where a multi-span identity could silently differ from the documented
    rule."""
    records = _records(
        (VECTORS["PS_first_occurrence"], 3, 0, 10),
        (VECTORS["PS_second_span"], 3, 20, 40))
    assert policy_uid_resolver.compute_derived_uid(
        "boundary", _context(), records) == VECTORS["PB_two_spans"]


def test_the_resolver_ignores_submitted_order_for_the_frozen_pb():
    """Reversed input, identical output -- extraction order is a forbidden
    identity input, asserted against a value the implementation did not
    produce."""
    records = _records(
        (VECTORS["PS_second_span"], 3, 20, 40),
        (VECTORS["PS_first_occurrence"], 3, 0, 10))
    assert policy_uid_resolver.compute_derived_uid(
        "boundary", _context(), records) == VECTORS["PB_two_spans"]


def test_the_resolver_composes_the_frozen_rc():
    records = _records((VECTORS["RC_cell_span"], 7, 2, 4))
    assert policy_uid_resolver.compute_derived_uid(
        "cell", _context(), records,
        parent_uid=VECTORS["RR_under_that_table"],
        column_key="rate") == VECTORS["RC_under_that_row"]


def test_every_kind_has_a_frozen_vector():
    """A new UID kind must arrive with an independent vector, or this fails --
    the coverage rule stated executably rather than in a comment."""
    covered = {uid.split("-", 1)[0] for uid in VECTORS.values()}
    assert covered == set(policy_uid.PREFIXES.values())
